### ISSUE TITLE
Is there a full screen button available to watch the videos in full screen.

### ISSUE THREAD

**Issue by rajeshjha96** [inthehand/InTheHand.Forms#54] opened 2019-03-10 22:20 UTC
Is there a full screen button available to watch the videos in full screen??/

**Comment by peterfoot** [comment] 2019-03-10 22:25
The is a button on the native iOS control. Not on the others currently.

**Comment by peterfoot** [comment] 2019-11-13 15:27
Duplicate of #14

**Closed as completed by peterfoot** 2019-11-13 15:27 UTC
Labels: enhancement
